# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=xfauxquarter,+d -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0x53,0x96,0x4a,0x4e]
fmulex.s.b f12, f21, f4, rtz
# CHECK-ASM: encoding: [0x53,0x2f,0xc5,0x57]
fmacex.s.b f30, f10, f28, rdn
