# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=xfauxalthalf,+d,+xfauxhalf -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0xd3,0x8a,0x2e,0x4c]
fmulex.s.ah f21, f29, f2, rne
# CHECK-ASM: encoding: [0x53,0x7e,0x40,0x55]
fmacex.s.ah f28, f0, f20, dyn
