# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=xfauxaltquarter,+d,+xfauxquarter,+xfauxvecquarter -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0x53,0x1f,0x5c,0x4f]
fmulex.s.ab f30, f24, f21, rtz
# CHECK-ASM: encoding: [0xd3,0xcd,0xa0,0x56]
fmacex.s.ab f27, f1, f10, rmm
