# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -filetype=obj -triple=riscv32  \
# RUN:   --mattr=-mattr=+d,+xfalthalf,+experimental-zfh,+xfquarter,+xfaltquarter,+xfvecsingle,+xfvechalf,+xfvecalthalf,+xfvecquarter \
# RUN:   | llvm-objdump -M no-aliases -d -r - \
# RUN:   --mattr=-mattr=+d,+xfalthalf,+experimental-zfh,+xfquarter,+xfaltquarter,+xfvecsingle,+xfvechalf,+xfvecalthalf,+xfvecquarter \
# RUN:   | FileCheck -check-prefixes=CHECK-DISASM %s

# Check smallfloat pseudo instructions

# CHECK-DISASM: flh     ft3, 0(tp)
flah ft3, (x4)
# CHECK-DISASM: fsh     ft5, 0(tp)
fsah ft5, (x4)
# CHECK-DISASM: flb     ft3, 0(tp)
flb ft3, (x4)
# CHECK-DISASM: fsb     ft5, 0(tp)
fsb ft5, (x4)
# CHECK-DISASM: flb     ft3, 0(tp)
flab ft3, (x4)
# CHECK-DISASM: fsb     ft5, 0(tp)
fsab ft5, (x4)
# CHECK-DISASM: fsgnj.h ft3, ft6, ft6
fmv.ah ft3, ft6
# CHECK-DISASM: fsgnjx.h        ft3, ft6, ft6
fabs.ah ft3, ft6
# CHECK-DISASM: fsgnjn.h        ft3, ft6, ft6
fneg.ah ft3, ft6
# CHECK-DISASM: fsgnj.b ft3, ft6, ft6
fmv.b ft3, ft6
# CHECK-DISASM: fsgnjx.b        ft3, ft6, ft6
fabs.b ft3, ft6
# CHECK-DISASM: fsgnjn.b        ft3, ft6, ft6
fneg.b ft3, ft6
# CHECK-DISASM: fsgnj.b ft3, ft6, ft6
fmv.ab ft3, ft6
# CHECK-DISASM: fsgnjx.b        ft3, ft6, ft6
fabs.ab ft3, ft6
# CHECK-DISASM: fsgnjn.b        ft3, ft6, ft6
fneg.ab ft3, ft6
# CHECK-DISASM: vfcpka.s.s      ft3, ft6, ft5
vfcpk.s.s.0 ft3, ft6, ft5
# CHECK-DISASM: vfcpka.s.d      ft3, ft6, ft5
vfcpk.s.d.0 ft3, ft6, ft5
# CHECK-DISASM: vfcpka.h.s      ft3, ft6, ft5
vfcpk.h.s.0 ft3, ft6, ft5
# CHECK-DISASM: vfcpkb.h.s      ft3, ft6, ft5
vfcpk.h.s.1 ft3, ft6, ft5
# CHECK-DISASM: vfcpka.h.d      ft3, ft6, ft5
vfcpk.h.d.0 ft3, ft6, ft5
# CHECK-DISASM: vfcpkb.h.d      ft3, ft6, ft5
vfcpk.h.d.1 ft3, ft6, ft5
# CHECK-DISASM: vfcpka.h.s      ft3, ft6, ft5
vfcpk.ah.s.0 ft3, ft6, ft5
# CHECK-DISASM: vfcpkb.h.s      ft3, ft6, ft5
vfcpk.ah.s.1 ft3, ft6, ft5
# CHECK-DISASM: vfcpka.h.d      ft3, ft6, ft5
vfcpk.ah.d.0 ft3, ft6, ft5
# CHECK-DISASM: vfcpkb.h.d      ft3, ft6, ft5
vfcpk.ah.d.1 ft3, ft6, ft5
# CHECK-DISASM: vfcpka.b.s      ft3, ft6, ft5
vfcpk.b.s.0 ft3, ft6, ft5
# CHECK-DISASM: vfcpkb.b.s      ft3, ft6, ft5
vfcpk.b.s.1 ft3, ft6, ft5
# CHECK-DISASM: vfcpkc.b.s      ft3, ft6, ft5
vfcpk.b.s.2 ft3, ft6, ft5
# CHECK-DISASM: vfcpkd.b.s      ft3, ft6, ft5
vfcpk.b.s.3 ft3, ft6, ft5
# CHECK-DISASM: vfcpka.b.d      ft3, ft6, ft5
vfcpk.b.d.0 ft3, ft6, ft5
# CHECK-DISASM: vfcpkb.b.d      ft3, ft6, ft5
vfcpk.b.d.1 ft3, ft6, ft5
# CHECK-DISASM: vfcpkc.b.d      ft3, ft6, ft5
vfcpk.b.d.2 ft3, ft6, ft5
# CHECK-DISASM: vfcpkd.b.d      ft3, ft6, ft5
vfcpk.b.d.3 ft3, ft6, ft5
