# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=xfauxvecsingle,+d -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0xb3,0x03,0xc7,0x8f]
vfsum.s f7, f14
# CHECK-ASM: encoding: [0x33,0x82,0xcb,0xaf]
vfnsum.s f4, f23
