# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=xfexpauxvecalthalf,+d,+xfexpauxvechalf,+xfauxvechalf -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0xb3,0x0f,0x6f,0x8f]
vfsumex.s.ah f31, f30
# CHECK-ASM: encoding: [0x33,0x08,0x6a,0xaf]
vfnsumex.s.ah f16, f20
# CHECK-ASM: encoding: [0xb3,0x0f,0xe8,0x96]
vfdotpex.s.ah f31, f16, f14
# CHECK-ASM: encoding: [0x33,0xc8,0x67,0x96]
vfdotpex.s.r.ah f16, f15, f6
# CHECK-ASM: encoding: [0x33,0x82,0xb6,0xba]
vfndotpex.s.ah f4, f13, f11
# CHECK-ASM: encoding: [0x33,0x4a,0x5b,0xbb]
vfndotpex.s.r.ah f20, f22, f21
