# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=xfexpauxvecaltquarter,+d,+xfexpauxvecquarter -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0x33,0xa9,0x76,0x8f]
vfsumex.h.ab f18, f13
# CHECK-ASM: encoding: [0x33,0x26,0x75,0xaf]
vfnsumex.h.ab f12, f10
# CHECK-ASM: encoding: [0xb3,0xad,0x79,0x96]
vfdotpex.h.ab f27, f19, f7
# CHECK-ASM: encoding: [0xb3,0x64,0xbd,0x96]
vfdotpex.h.r.ab f9, f26, f11
# CHECK-ASM: encoding: [0xb3,0x25,0xdc,0xbb]
vfndotpex.h.ab f11, f24, f29
# CHECK-ASM: encoding: [0xb3,0x6c,0xe4,0xbb]
vfndotpex.h.r.ab f25, f8, f30
# CHECK-ASM: encoding: [0xb3,0x24,0x70,0x8f]
vfsumex.ah.ab f9, f0
# CHECK-ASM: encoding: [0x33,0xaa,0x70,0xaf]
vfnsumex.ah.ab f20, f1
# CHECK-ASM: encoding: [0x33,0xa4,0x71,0x97]
vfdotpex.ah.ab f8, f3, f23
# CHECK-ASM: encoding: [0xb3,0xe6,0x99,0x97]
vfdotpex.ah.r.ab f13, f19, f25
# CHECK-ASM: encoding: [0x33,0x2e,0x05,0xbb]
vfndotpex.ah.ab f28, f10, f16
# CHECK-ASM: encoding: [0xb3,0x69,0x22,0xbb]
vfndotpex.ah.r.ab f19, f4, f18
