# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=xfauxvecalthalf,+d,+xfauxvechalf -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0xb3,0x2e,0xee,0x8f]
vfsum.ah f29, f28
# CHECK-ASM: encoding: [0x33,0xa7,0xe3,0xaf]
vfnsum.ah f14, f7
