# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=xfexpauxvechalf,+d -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0x33,0x03,0x66,0x8f]
vfsumex.s.h f6, f12
# CHECK-ASM: encoding: [0x33,0x88,0x69,0xaf]
vfnsumex.s.h f16, f19
# CHECK-ASM: encoding: [0xb3,0x04,0x66,0x97]
vfdotpex.s.h f9, f12, f22
# CHECK-ASM: encoding: [0x33,0xc7,0x77,0x97]
vfdotpex.s.r.h f14, f15, f23
# CHECK-ASM: encoding: [0xb3,0x01,0x6d,0xba]
vfndotpex.s.h f3, f26, f6
# CHECK-ASM: encoding: [0x33,0xc1,0x93,0xba]
vfndotpex.s.r.h f2, f7, f9
