# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=xfauxhalf,+d -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0x53,0x43,0x58,0x4c]
fmulex.s.h f6, f16, f5, rmm
# CHECK-ASM: encoding: [0xd3,0x0f,0x53,0x54]
fmacex.s.h f31, f6, f5, rne
