# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=xfauxvecquarter,+d -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0x33,0xb8,0x7e,0x8e]
vfsum.b f16, f29
# CHECK-ASM: encoding: [0xb3,0x3b,0x78,0xae]
vfnsum.b f23, f16
