# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=xfauxvechalf,+d -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0x33,0xac,0xe1,0x8f]
vfsum.h f24, f3
# CHECK-ASM: encoding: [0xb3,0xa2,0xe9,0xaf]
vfnsum.h f5, f19
