# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv32 -mattr=+xsmallfloat,+experimental-zfh -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM,CHECK-ASM-AND-OBJ %s
# RUN: llvm-mc -filetype=obj -triple=riscv32 -mattr=+xsmallfloat,+experimental-zfh < %s \
# RUN:     | llvm-objdump --mattr=+xsmallfloat,+experimental-zfh -M no-aliases -d -r - \
# RUN:     | FileCheck --check-prefix=CHECK-ASM-AND-OBJ %s

# Smallfloat instructions that alias a zfh instruction

# CHECK-ASM-AND-OBJ: flh fs3, 609(a4)
# CHECK-ASM: encoding: [0x87,0x19,0x17,0x26]
flah f19, 609(x14)
# CHECK-ASM-AND-OBJ: fsh ft2, 1827(zero)
# CHECK-ASM: encoding: [0xa7,0x11,0x20,0x72]
fsah f2, 1827(x0)
